name: Validate PR is mergeable

on:
  pull_request_review_comment:
    types: [ created ]

jobs:
  check-kirby-ingest:
    runs-on: ubuntu-latest
    # if: contains(github.event.comment.body, '/status rollup')
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Report success status
        run: |
          exit 0
